server:
  port: 4000
  servlet:
    context-path: /api
spring:
  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher
  application:
    name: agency-service
  devtools:
    LiveReload:
      enable: false
  flyway:
    baseline-on-migrate: true

